language: node_js
node_js:
  - "8"
cache:
  directories:
  - lambda/node_modules
install:
  - npm install bespoken-tools -g
  - npm install codecov -g
  - cd lambda && npm install && cd ..
script:
 - bst test
 - codecov