language: node_js
node_js:
  - "11"
cache:
  directories:
  - lambda/node_modules
install:
  - npm install bespoken-tools -d
  - npm install codecov -d
  - cd lambda && npm install && cd ..
script:
 - npm run test
 - codecov
env:
 - DEBUG=nock.*