PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX arces-monitor: <ttp://wot.arces.unibo.it/monitor#>
INSERT DATA
{ 
    arces-monitor:temperature a sosa:ObservableProperty .
    arces-monitor:humidity a sosa:ObservableProperty .
    arces-monitor:moisture a sosa:ObservableProperty .
    arces-monitor:voltage a sosa:ObservableProperty .
    arces-monitor:pressure a sosa:ObservableProperty .
    arces-monitor:swamp_devices_moisture1_up_Moisture_Signal_to_Supply_Perc sosa:observedProperty arces-monitor:moisture .
    arces-monitor:001BC50C700009BB-DASH7-Temperature sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore20 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore19 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore18 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore17 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore16 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore15 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore14 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore13 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore12D sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore11 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore10 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore9 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore8 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore7 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore6 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore5 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore4 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore3 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore2 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleCore1 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerMml6 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerMml5 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerMml4 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerMml3 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerMml2 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerMml1 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerGiove6 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerGiove5 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerGiove4 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerGiove3 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerGiove2 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerGiove1 sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerMmlHDDSda sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerMmlHDDSdb sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerGioveHDDSda sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerGioveHDDSdb sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerGioveHDDSdc sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerGioveHDDSdd sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerGioveHDDSdf sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerGioveHDDSdg sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerGioveHDDSdh sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerSambaHDDSda sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerSambaHDDSdb sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleHDDSda sosa:observedProperty arces-monitor:temperature .
    arces-monitor:ServerErcoleHDDSdb sosa:observedProperty arces-monitor:temperature .
    arces-monitor:5CCF7F15676D-temperature sosa:observedProperty arces-monitor:temperature .
    arces-monitor:5CCF7F15676D-humidity sosa:observedProperty arces-monitor:humidity .
    arces-monitor:5CCF7F1B599E-temperature sosa:observedProperty arces-monitor:temperature .
    arces-monitor:5CCF7F1B599E-humidity sosa:observedProperty arces-monitor:humidity .
    arces-monitor:5CCF7F151DC9-temperature sosa:observedProperty arces-monitor:temperature .
    arces-monitor:5CCF7F1B58AC-temperature sosa:observedProperty arces-monitor:temperature .
    arces-monitor:5CCF7F1B58AC-humidity sosa:observedProperty arces-monitor:humidity .
    arces-monitor:Italy-Site1-SoilMoisture sosa:observedProperty arces-monitor:moisture .
    arces-monitor:Italy-Site1-Temperature sosa:observedProperty arces-monitor:temperature .
    arces-monitor:swamp_devices_moisture1_up_Moisture_Supply_Voltage sosa:observedProperty arces-monitor:voltage .
    arces-monitor:swamp_devices_moisture1_up_Node_Supply_Voltage sosa:observedProperty arces-monitor:voltage .
    arces-monitor:001BC50C700009CD-DASH7-Temperature sosa:observedProperty arces-monitor:temperature .
    arces-monitor:Italy-Site1-Pressure sosa:observedProperty arces-monitor:pressure .
}