PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX arces-monitor: <http://wot.arces.unibo.it/monitor#>
PREFIX m3lite: <http://purl.org/iot/vocab/m3-lite#>
PREFIX seasb: <https://w3id.org/seas/>
PREFIX saref: <http://ontology.tno.nl/saref/#>

INSERT DATA
{
    arces-monitor:swamp_devices_moisture1_up_Moisture_Signal_to_Supply_Perc saref:measuresProperty m3lite:SoilHumidity .
    arces-monitor:001BC50C700009BB-DASH7-Temperature saref:measuresProperty m3lite:BuildingTemperature .
    arces-monitor:ServerErcoleCore20 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore19 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore18 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore17 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore16 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore15 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore14 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore13 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore12D saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore11 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore10 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore9 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore8 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore7 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore6 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore5 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore4 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore3 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore2 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleCore1 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerMml6 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerMml5 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerMml4 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerMml3 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerMml2 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerMml1 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerGiove6 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerGiove5 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerGiove4 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerGiove3 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerGiove2 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerGiove1 saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerMmlHDDSda saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerMmlHDDSdb saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerGioveHDDSda saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerGioveHDDSdb saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerGioveHDDSdc saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerGioveHDDSdd saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerGioveHDDSdf saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerGioveHDDSdg saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerGioveHDDSdh saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerSambaHDDSda saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerSambaHDDSdb saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleHDDSda saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:ServerErcoleHDDSdb saref:measuresProperty m3lite:BoardTemperature .
    arces-monitor:5CCF7F15676D-temperature saref:measuresProperty m3lite:BuildingTemperature .
    arces-monitor:5CCF7F15676D-humidity saref:measuresProperty m3lite:Humidity .
    arces-monitor:5CCF7F1B599E-temperature saref:measuresProperty m3lite:Temperature .
    arces-monitor:5CCF7F1B599E-humidity saref:measuresProperty m3lite:Humidity .
    arces-monitor:5CCF7F151DC9-temperature saref:measuresProperty m3lite:BuildingTemperature .
    arces-monitor:5CCF7F1B58AC-temperature saref:measuresProperty m3lite:BuildingTemperature .
    arces-monitor:5CCF7F1B58AC-humidity saref:measuresProperty m3lite:Humidity .
    arces-monitor:Italy-Site1-SoilMoisture saref:measuresProperty m3lite:SoilHumidity .
    arces-monitor:Italy-Site1-Temperature saref:measuresProperty m3lite:BuildingTemperature .
    arces-monitor:swamp_devices_moisture1_up_Moisture_Supply_Voltage saref:measuresProperty m3lite:Voltage .
    arces-monitor:swamp_devices_moisture1_up_Node_Supply_Voltage saref:measuresProperty m3lite:Voltage .
    arces-monitor:001BC50C700009CD-DASH7-Temperature saref:measuresProperty m3lite:BuildingTemperature .
    arces-monitor:Italy-Site1-Pressure saref:measuresProperty m3lite:AtmosphericPressure .
}





