CLEAR GRAPH <http://devidtest/graph>

INSERT {
  GRAPH <http://devidtest/graph> {
    m3lite:Temperature a sosa:ObservableProperty .
    m3lite:BoardTemperature a sosa:ObservableProperty .
    m3lite:BuildingTemperature a sosa:ObservableProperty .
    m3lite:SoilHumidity a sosa:ObservableProperty .
    m3lite:Humidity a sosa:ObservableProperty .
    m3lite:Voltage a sosa:ObservableProperty .
    m3lite:AtmosphericPressure a sosa:ObservableProperty .
    m3lite:BatteryLevel a sosa:ObservableProperty .

    arces-monitor:alexa-actuator a sosa:Actuator ;
      sosa:madeActuation <actuation://devid-temp-1> ;
      sosa:madeActuation <actuation://devid-temp-2> ;
      sosa:madeActuation <actuation://devid-temp-3> ;
      sosa:madeActuation <actuation://devid-temp-4> ;
      sosa:madeActuation <actuation://devid-temp-5> ;
      sosa:madeActuation <actuation://devid-temp-6> ;
      sosa:madeActuation <actuation://devid-temp-7> ;
      sosa:madeActuation <actuation://devid-temp-8> ;
      sosa:madeActuation <actuation://devid-temp-9> .

    arces-monitor:devid-temp-1-1 a sosa:Observation ;
      rdf:label "Devid Test 1-1(Temperature)" ;
      sosa:madeBySensor <sensor://devid-temp-1-1> ;
      sosa:hasResult <result://devid-temp-1-1> ;
      sosa:hasFeatureOfInterest <place://devid-temp-1> ;
      arces-monitor:hasUpdateInterval <interval://devid-temp-1-1> .
    <interval://devid-temp-1-1> a qudt-1-1:QuantityValue ;
        qudt-1-1:unit qudt-unit-1-1:MilliSecond ;
        qudt-1-1:numericValue 3600000 .
    <result://devid-temp-1-1> a qudt-1-1:QuantityValue ;
      qudt-1-1:numericValue 0.36 .
    <place://devid-temp-1> a schema:Place ;
      schema:name "DEVID HOUSE 1" .
    <sensor://devid-temp-1-1> a sosa:Sensor ;
      sosa:observes m3lite:Temperature ;
      ssn:hasProperty <sensor://devid-temp-1-1#state> .
    <sensor://devid-temp-1-1#state> a sosa:ActuatableProperty ;
      sosa:isActedOnBy <actuation://devid-temp-1-1> .
    <actuation://devid-temp-1-1> a sosa:Actuation ;
      sosa:actsOnProperty  <sensor://devid-temp-1-1#state> ;
      sosa:actuationMadeBy arces-monitor:alexa-actuator ; 
      sosa:hasSimpleResult false ;
      sosa:resultTime "2017-04-17T17:24:00+02:00" .

    arces-monitor:devid-temp-1-2 a sosa:Observation ;
      rdf:label "Devid Test 1-2(Temperature)" ;
      sosa:madeBySensor <sensor://devid-temp-1-2> ;
      sosa:hasResult <result://devid-temp-1-2> ;
      sosa:hasFeatureOfInterest <place://devid-temp-1> ;
      arces-monitor:hasUpdateInterval <interval://devid-temp-1-2> .
    <interval://devid-temp-1-2> a qudt-1-1:QuantityValue ;
        qudt-1-1:unit qudt-unit-1-1:MilliSecond ;
        qudt-1-1:numericValue 3600000 .
    <result://devid-temp-1-2> a qudt-1-1:QuantityValue ;
      qudt-1-1:numericValue 0.36 .
    <place://devid-temp-1> a schema:Place ;
      schema:name "DEVID HOUSE 1" .
    <sensor://devid-temp-1-2> a sosa:Sensor ;
      sosa:observes m3lite:Temperature ;
      ssn:hasProperty <sensor://devid-temp-1-2#state> .
    <sensor://devid-temp-1-2#state> a sosa:ActuatableProperty ;
      sosa:isActedOnBy <actuation://devid-temp-1-2> .
    <actuation://devid-temp-1-2> a sosa:Actuation ;
      sosa:actsOnProperty  <sensor://devid-temp-1-2#state> ;
      sosa:actuationMadeBy arces-monitor:alexa-actuator ; 
      sosa:hasSimpleResult false ;
      sosa:resultTime "2017-04-17T17:24:00+02:00" .

    arces-monitor:devid-temp-2-1 a sosa:Observation ;
      rdf:label "Devid Test 2(Temperature)" ;
      sosa:madeBySensor <sensor://devid-temp-2-1> ;
      sosa:hasResult <result://devid-temp-2-1> ;
      sosa:hasFeatureOfInterest <place://devid-temp-2> ;
      arces-monitor:hasUpdateInterval <interval://devid-temp-2-1> .
    <interval://devid-temp-2-1> a qudt-1-1:QuantityValue ;
        qudt-1-1:unit qudt-unit-1-1:MilliSecond ;
        qudt-1-1:numericValue 3600000 .
    <result://devid-temp-2-1> a qudt-1-1:QuantityValue ;
      qudt-1-1:numericValue 0.36 .
    <place://devid-temp-2> a schema:Place ;
      schema:name "DEVID HOUSE 2" .
    <sensor://devid-temp-2-1> a sosa:Sensor ;
      sosa:observes m3lite:Temperature ;
      ssn:hasProperty <sensor://devid-temp-2-1#state> .
    <sensor://devid-temp-2-1#state> a sosa:ActuatableProperty ;
      sosa:isActedOnBy <actuation://devid-temp-2-1> .
    <actuation://devid-temp-2-1> a sosa:Actuation ;
      sosa:actsOnProperty  <sensor://devid-temp-2-1#state> ;
      sosa:actuationMadeBy arces-monitor:alexa-actuator ; 
      sosa:hasSimpleResult false ;
      sosa:resultTime "2017-04-16T17:24:00+02:00" .

    arces-monitor:devid-temp-3-1 a sosa:Observation ;
      rdf:label "Devid Test 3(Temperature)" ;
      sosa:madeBySensor <sensor://devid-temp-3-1> ;
      sosa:hasResult <result://devid-temp-3-1> ;
      sosa:hasFeatureOfInterest <place://devid-temp-3> ;
      arces-monitor:hasUpdateInterval <interval://devid-temp-3-1> .
    <interval://devid-temp-3-1> a qudt-1-1:QuantityValue ;
        qudt-1-1:unit qudt-unit-1-1:MilliSecond ;
        qudt-1-1:numericValue 3600000 .
    <result://devid-temp-3-1> a qudt-1-1:QuantityValue ;
      qudt-1-1:numericValue 0.36 .
    <place://devid-temp-3> a schema:Place ;
      schema:name "DEVID HOUSE 3" .
    <sensor://devid-temp-3-1> a sosa:Sensor ;
      sosa:observes m3lite:Temperature ;
      ssn:hasProperty <sensor://devid-temp-3-1#state> .
    <sensor://devid-temp-3-1#state> a sosa:ActuatableProperty ;
      sosa:isActedOnBy <actuation://devid-temp-3-1> .
    <actuation://devid-temp-3-1> a sosa:Actuation ;
      sosa:actsOnProperty  <sensor://devid-temp-3-1#state> ;
      sosa:actuationMadeBy arces-monitor:alexa-actuator ; 
      sosa:hasSimpleResult false ;
      sosa:resultTime "2017-04-15T17:24:00+02:00" .

    arces-monitor:devid-temp-4 a sosa:Observation ;
      rdf:label "Devid Test 4(BoardTemperature)" ;
      sosa:madeBySensor <sensor://devid-temp-4> ;
      sosa:hasResult <result://devid-temp-4> ;
      sosa:hasFeatureOfInterest <place://devid-temp-4> ;
      arces-monitor:hasUpdateInterval <interval://devid-temp4> .
    <interval://devid-temp4> a qudt-1-1:QuantityValue ;
        qudt-1-1:unit qudt-unit-1-1:MilliSecond ;
        qudt-1-1:numericValue 7200000 .
    <result://devid-temp-4> a qudt-1-1:QuantityValue ;
      qudt-1-1:numericValue 0.40 .
    <place://devid-temp-4> a schema:Place ;
      schema:name "DEVID HOUSE 4" .
    <sensor://devid-temp-4> a sosa:Sensor ;
      sosa:observes m3lite:BoardTemperature ;
      ssn:hasProperty <sensor://devid-temp-4#state> .
    <sensor://devid-temp-4#state> a sosa:ActuatableProperty ;
      sosa:isActedOnBy <actuation://devid-temp-4> .
    <actuation://devid-temp-4> a sosa:Actuation ;
      sosa:actsOnProperty  <sensor://devid-temp-4#state> ;
      sosa:actuationMadeBy arces-monitor:alexa-actuator ; 
      sosa:hasSimpleResult false ;
      sosa:resultTime "2017-04-08T17:24:00+02:00" .

    arces-monitor:devid-temp-5 a sosa:Observation ;
      rdf:label "Devid Test 5(SoilHumidity)" ;
      sosa:madeBySensor <sensor://devid-temp-5> ;
      sosa:hasResult <result://devid-temp-5> ;
      sosa:hasFeatureOfInterest <place://devid-temp-5> ;
      arces-monitor:hasUpdateInterval <interval://devid-temp-5> .
    <interval://devid-temp-5> a qudt-1-1:QuantityValue ;
        qudt-1-1:unit qudt-unit-1-1:MilliSecond ;
        qudt-1-1:numericValue 7200000 .
    <result://devid-temp-5> a qudt-1-1:QuantityValue ;
      qudt-1-1:numericValue 36 .
    <place://devid-temp-5> a schema:Place ;
      schema:name "DEVID HOUSE 5" .
    <sensor://devid-temp-5> a sosa:Sensor ;
      sosa:observes m3lite:SoilHumidity ;
      ssn:hasProperty <sensor://devid-temp-5#state> .
    <sensor://devid-temp-5#state> a sosa:ActuatableProperty ;
      sosa:isActedOnBy <actuation://devid-temp-5> .
    <actuation://devid-temp-5> a sosa:Actuation ;
      sosa:actsOnProperty  <sensor://devid-temp-5#state> ;
      sosa:actuationMadeBy arces-monitor:alexa-actuator ; 
      sosa:hasSimpleResult false ;
      sosa:resultTime "2017-04-18T17:24:00+02:00" .
      
    arces-monitor:devid-temp-6 a sosa:Observation ;
      rdf:label "Devid Test 6(Humidity)" ;
      sosa:madeBySensor <sensor://devid-temp-6> ;
      sosa:hasResult <result://devid-temp-6> ;
      sosa:hasFeatureOfInterest <place://devid-temp-6> ;
      arces-monitor:hasUpdateInterval <interval://devid-temp-6> .
    <interval://devid-temp-6> a qudt-1-1:QuantityValue ;
        qudt-1-1:unit qudt-unit-1-1:MilliSecond ;
        qudt-1-1:numericValue 3600000 .
    <result://devid-temp-6> a qudt-1-1:QuantityValue ;
      qudt-1-1:numericValue 90 .
    <place://devid-temp-6> a schema:Place ;
      schema:name "DEVID HOUSE 6" .
    <sensor://devid-temp-6> a sosa:Sensor ;
      sosa:observes m3lite:Humidity ;
      ssn:hasProperty <sensor://devid-temp-6#state> .
    <sensor://devid-temp-6#state> a sosa:ActuatableProperty ;
      sosa:isActedOnBy <actuation://devid-temp-6> .
    <actuation://devid-temp-6> a sosa:Actuation ;
      sosa:actsOnProperty  <sensor://devid-temp-6#state> ;
      sosa:actuationMadeBy arces-monitor:alexa-actuator ; 
      sosa:hasSimpleResult false ;
      sosa:resultTime "2017-04-18T17:24:00+02:00" .

    arces-monitor:devid-temp-7 a sosa:Observation ;
      rdf:label "Devid Test 7(Voltage)" ;
      sosa:madeBySensor <sensor://devid-temp-7> ;
      sosa:hasResult <result://devid-temp-7> ;
      sosa:hasFeatureOfInterest <place://devid-temp-7> ;
      arces-monitor:hasUpdateInterval <interval://devid-temp-7> .
    <interval://devid-temp-7> a qudt-1-1:QuantityValue ;
        qudt-1-1:unit qudt-unit-1-1:MilliSecond ;
        qudt-1-1:numericValue 3600000 .
    <result://devid-temp-7> a qudt-1-1:QuantityValue ;
      qudt-1-1:numericValue 20 .
    <place://devid-temp-7> a schema:Place ;
      schema:name "DEVID HOUSE 7" .
    <sensor://devid-temp-7> a sosa:Sensor ;
      sosa:observes m3lite:Voltage ;
      ssn:hasProperty <sensor://devid-temp-7#state> .
    <sensor://devid-temp-7#state> a sosa:ActuatableProperty ;
      sosa:isActedOnBy <actuation://devid-temp-7> .
    <actuation://devid-temp-7> a sosa:Actuation ;
      sosa:actsOnProperty  <sensor://devid-temp-7#state> ;
      sosa:actuationMadeBy arces-monitor:alexa-actuator ; 
      sosa:hasSimpleResult false ;
      sosa:resultTime "2017-04-28T17:24:00+02:00" .

    arces-monitor:devid-temp-8 a sosa:Observation ;
      rdf:label "Devid Test 8(AtmosphericPressure)" ;
      sosa:madeBySensor <sensor://devid-temp-8> ;
      sosa:hasResult <result://devid-temp-8> ;
      sosa:hasFeatureOfInterest <place://devid-temp-8> ;
      arces-monitor:hasUpdateInterval <interval://devid-temp-8> .
    <interval://devid-temp-8> a qudt-1-1:QuantityValue ;
        qudt-1-1:unit qudt-unit-1-1:MilliSecond ;
        qudt-1-1:numericValue 7200000 .
    <result://devid-temp-8> a qudt-1-1:QuantityValue ;
      qudt-1-1:numericValue 24 .
    <place://devid-temp-8> a schema:Place ;
      schema:name "DEVID HOUSE 8" .
    <sensor://devid-temp-8> a sosa:Sensor ;
      sosa:observes m3lite:AtmosphericPressure ;
      ssn:hasProperty <sensor://devid-temp-8#state> .
    <sensor://devid-temp-8#state> a sosa:ActuatableProperty ;
      sosa:isActedOnBy <actuation://devid-temp-8> .
    <actuation://devid-temp-8> a sosa:Actuation ;
      sosa:actsOnProperty  <sensor://devid-temp-8#state> ;
      sosa:actuationMadeBy arces-monitor:alexa-actuator ; 
      sosa:hasSimpleResult false ;
      sosa:resultTime "2017-04-11T17:24:00+02:00" .

    arces-monitor:devid-temp-9 a sosa:Observation ;
      rdf:label "Devid Test 9(BatteryLevel)" ;
      sosa:madeBySensor <sensor://devid-temp-9> ;
      sosa:hasResult <result://devid-temp-9> ;
      sosa:hasFeatureOfInterest <place://devid-temp-9> ;
      arces-monitor:hasUpdateInterval <interval://devid-temp-9> .
    <interval://devid-temp-9> a qudt-1-1:QuantityValue ;
        qudt-1-1:unit qudt-unit-1-1:MilliSecond ;
        qudt-1-1:numericValue 3600000 .
    <result://devid-temp-9> a qudt-1-1:QuantityValue ;
      qudt-1-1:numericValue 99 .
    <place://devid-temp-9> a schema:Place ;
      schema:name "DEVID HOUSE 9" .
    <sensor://devid-temp-9> a sosa:Sensor ;
      sosa:observes m3lite:BatteryLevel ;
      ssn:hasProperty <sensor://devid-temp-9#state> .
    <sensor://devid-temp-9#state> a sosa:ActuatableProperty ;
      sosa:isActedOnBy <actuation://devid-temp-9> .
    <actuation://devid-temp-9> a sosa:Actuation ;
      sosa:actsOnProperty  <sensor://devid-temp-9#state> ;
      sosa:actuationMadeBy arces-monitor:alexa-actuator ; 
      sosa:hasSimpleResult false ;
      sosa:resultTime "2017-04-19T17:24:00+02:00" .
  }
}